### ISSUE TITLE
Build for z3 broken with latest changes

### ISSUE THREAD

**Issue by hawkeyexp** [Sony-Stock-CM/local_manifests#1]
device/sony/shinano-common/shinano.mk:72: *** Mehrfache Target-Muster.  Schluss.

**Comment by russel5** [comment]
read my comment in the shinano.mk file
https://github.com/Sony-Stock-CM/android_device_sony_shinano-common/commit/80d01abbc98a2e4ab0376146ccca4763029b0030

**Comment by nailyk-fr** [comment]
[Done](https://review.lineageos.org/179467).
